---
- hosts: all
  become : yes
  tasks:
  - name:
    apt:
      update_cache: yes

- hosts: app
  become: yes
  vars:
    folderpath: /home/ansible/nodesetup
  tasks :
  - name: creating nodejs directory
    file:
      path: "{{ folderpath }}"
      state : directory
      mode : 0755
  - name: download node js app
    command : "curl -sL https://deb.nodesource.com/setup_8.x -o {{folderpath}}/nodesource_setup.sh "
  - name: execute  download shell script
    command : "sudo bash {{folderpath}}/nodesource_setup.sh"
  - name: isntall node js
    apt:
      name: nodejs
      state: present
  - name:
    template:
      src : "templates/hello.js.j2"
      dest : "{{folderpath}}/hello.js"
  - name: install pm2
    npm :
      name : pm2
      global : yes
  - name : start nodejs app
    command: "pm2 start {{folderpath}}/hello.js"
- hosts : web
  become : yes 
  vars :
    webserver_dns_name : "ec2-54-201-6-109.us-west-2.compute.amazonaws.com"
    app_server : "ec2-54-190-43-41.us-west-2.compute.amazonaws.com"
  tasks :
  - name: install nginx
    apt:
      name: nginx
      state: present
  - name : copy default file
    template: 
      src: "templates/default.j2"
      dest: "/etc/nginx/sites-available/default"
    notify : Restart Nginx
  handlers:
  - name : Restart Nginx
    service :
      name : nginx
      state : restarted
