---
# tasks file for appserver
- name: creating nodejs directory
  file:
    path: "{{ folderpath }}"
    state : directory
    mode : 0755
- name: download node js app
  command : "curl -sL https://deb.nodesource.com/setup_{{ version }}.x -o {{folderpath}}/nodesource_setup.sh "
- name: execute  download shell script
  command : "sudo bash {{folderpath}}/nodesource_setup.sh"
- name: isntall node js
  apt:
    name: nodejs
    state: present
- name:
  template:
    src : "templates/hello.js.j2"
    dest : "{{folderpath}}/hello.js"
- name: install pm2
  npm :
    name : pm2
    global : yes
- name : start nodejs app
  command: "pm2 start {{folderpath}}/hello.js"
